version: "3"

services:
  app:
    container_name: phpunit-test-app
    image: php:7.4-fpm
    command: php -S 0.0.0.0:8000 /app/index.php
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  phpunit:
    container_name: phpunit
    image: php:7.4-cli
    restart: 'no'
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
    command: phpunit tests

  composer:
    restart: 'no'
    image: composer/composer
    command: install
    volumes:
      - .:/app