version: "3"

services:
  app:
    container_name: phpunit-test-app
    image: php:7.4-fpm
    command: php -S 0.0.0.0:8000 /app/index.php
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  composer:
    restart: 'no'
    image: composer/composer
    command: install
    volumes:
      - .:/app